'use client';

import { useState, useRef } from 'react';
import { Sparkles, Copy, Download, Loader2, ChevronRight, Brain, Zap, Shield, Check } from 'lucide-react';
import MOMDisplay from '@/components/MOMDisplay';

interface ActionItem {
  task: string;
  owner: string;
  deadline: string;
}

interface MOMData {
  summary: string;
  discussionPoints: string[];
  decisions: string[];
  actionItems: ActionItem[];
  risks: string[];
  nextSteps: string[];
}

export default function HomePage() {
  const [transcript, setTranscript] = useState('');
  const [mom, setMom] = useState<MOMData | null>(null);
  const [generatedAt, setGeneratedAt] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);
  const momRef = useRef<HTMLDivElement>(null);

  async function handleGenerate() {
    if (!transcript.trim()) {
      setError('Please paste your meeting transcript first.');
      return;
    }
    setError('');
    setLoading(true);
    setMom(null);

    try {
      const res = await fetch('/api/generate-mom', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ transcript }),
      });

      const data = await res.json();

      if (!res.ok || data.error) {
        setError(data.error || 'Failed to generate MOM. Please try again.');
        return;
      }

      setMom(data.mom);
      setGeneratedAt(new Date().toLocaleString('en-IN', {
        year: 'numeric', month: 'long', day: 'numeric',
        hour: '2-digit', minute: '2-digit',
      }));

      setTimeout(() => {
        momRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }, 100);
    } catch {
      setError('Something went wrong. Please try again.');
    } finally {
      setLoading(false);
    }
  }

  function buildPlainText(): string {
    if (!mom) return '';
    const lines: string[] = [];

    lines.push('MINUTES OF MEETING');
    lines.push('Generated by ROCK — MOM AI by Varun Jain');
    lines.push(`Date: ${generatedAt}`);
    lines.push('');
    lines.push('─────────────────────────────────────────');
    lines.push('SUMMARY');
    lines.push('─────────────────────────────────────────');
    lines.push(mom.summary);
    lines.push('');

    if (mom.discussionPoints.length > 0) {
      lines.push('─────────────────────────────────────────');
      lines.push('DISCUSSION POINTS');
      lines.push('─────────────────────────────────────────');
      mom.discussionPoints.forEach((p, i) => lines.push(`${i + 1}. ${p}`));
      lines.push('');
    }

    if (mom.decisions.length > 0) {
      lines.push('─────────────────────────────────────────');
      lines.push('DECISIONS MADE');
      lines.push('─────────────────────────────────────────');
      mom.decisions.forEach((d) => lines.push(`• ${d}`));
      lines.push('');
    }

    if (mom.actionItems.length > 0) {
      lines.push('─────────────────────────────────────────');
      lines.push('ACTION ITEMS');
      lines.push('─────────────────────────────────────────');
      mom.actionItems.forEach((a) => {
        lines.push(`Task: ${a.task}`);
        lines.push(`  Owner: ${a.owner}  |  Deadline: ${a.deadline}`);
      });
      lines.push('');
    }

    if (mom.risks.length > 0) {
      lines.push('─────────────────────────────────────────');
      lines.push('RISKS & CONCERNS');
      lines.push('─────────────────────────────────────────');
      mom.risks.forEach((r) => lines.push(`• ${r}`));
      lines.push('');
    }

    if (mom.nextSteps.length > 0) {
      lines.push('─────────────────────────────────────────');
      lines.push('NEXT STEPS');
      lines.push('─────────────────────────────────────────');
      mom.nextSteps.forEach((s, i) => lines.push(`${i + 1}. ${s}`));
      lines.push('');
    }

    return lines.join('\n');
  }

  async function handleCopy() {
    const text = buildPlainText();
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function handleDownload() {
    if (!mom) return;

    // Build a simple RTF document that opens in Word
    const lines: string[] = [];
    lines.push('{\\rtf1\\ansi\\deff0');
    lines.push('{\\fonttbl{\\f0\\froman\\fcharset0 Times New Roman;}{\\f1\\fswiss\\fcharset0 Arial;}}');
    lines.push('{\\colortbl ;\\red0\\green86\\blue175;\\red30\\green41\\blue59;}');

    const rtf = (s: string) => s.replace(/\\/g, '\\\\').replace(/{/g, '\\{').replace(/}/g, '\\}');

    lines.push('\\f1\\fs28\\b\\cf1 MINUTES OF MEETING\\b0\\cf2\\par');
    lines.push('\\fs20 Generated by ROCK \\emdash MOM AI by Varun Jain\\par');
    lines.push(`\\fs18\\i Date: ${rtf(generatedAt)}\\i0\\par\\par`);

    function heading(title: string) {
      lines.push(`\\fs22\\b\\cf1 ${rtf(title)}\\b0\\cf2\\par`);
      lines.push('\\brdrb\\brdrs\\brdrw10\\brsp20 \\par');
    }

    function body(text: string) {
      lines.push(`\\fs20 ${rtf(text)}\\par`);
    }

    heading('SUMMARY');
    body(mom.summary);
    lines.push('\\par');

    if (mom.discussionPoints.length > 0) {
      heading('DISCUSSION POINTS');
      mom.discussionPoints.forEach((p, i) => body(`${i + 1}. ${p}`));
      lines.push('\\par');
    }

    if (mom.decisions.length > 0) {
      heading('DECISIONS MADE');
      mom.decisions.forEach((d) => body(`\\bullet  ${d}`));
      lines.push('\\par');
    }

    if (mom.actionItems.length > 0) {
      heading('ACTION ITEMS');
      mom.actionItems.forEach((a) => {
        lines.push(`\\fs20\\b ${rtf(a.task)}\\b0\\par`);
        body(`  Owner: ${a.owner}   |   Deadline: ${a.deadline}`);
      });
      lines.push('\\par');
    }

    if (mom.risks.length > 0) {
      heading('RISKS & CONCERNS');
      mom.risks.forEach((r) => body(`\\bullet  ${r}`));
      lines.push('\\par');
    }

    if (mom.nextSteps.length > 0) {
      heading('NEXT STEPS');
      mom.nextSteps.forEach((s, i) => body(`${i + 1}. ${s}`));
      lines.push('\\par');
    }

    lines.push('}');
    const content = lines.join('\n');

    const blob = new Blob([content], { type: 'application/rtf' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `MOM_${new Date().toISOString().split('T')[0]}.doc`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="min-h-screen bg-[#f8fafc]">
      {/* Navigation */}
      <nav className="sticky top-0 z-50 bg-white/80 backdrop-blur-md border-b border-slate-100">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center">
              <Brain className="w-4.5 h-4.5 text-white w-[18px] h-[18px]" />
            </div>
            <div>
              <span className="font-bold text-slate-900 text-lg leading-none">ROCK</span>
              <span className="text-blue-600 font-bold text-lg leading-none"> MOM AI</span>
            </div>
          </div>
          <div className="hidden sm:flex items-center gap-1 text-xs text-slate-500">
            <span>by</span>
            <span className="font-semibold text-slate-700">Varun Jain</span>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="relative overflow-hidden bg-white border-b border-slate-100">
        <div className="absolute inset-0 bg-gradient-to-br from-blue-50 via-white to-slate-50 pointer-events-none" />
        <div className="relative max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-20">
          <div className="text-center max-w-3xl mx-auto">
            <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-blue-50 border border-blue-100 text-blue-700 text-xs font-medium mb-6">
              <Sparkles className="w-3.5 h-3.5" />
              Powered by Google Gemini AI
            </div>
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold text-slate-900 leading-tight mb-4">
              AI Meeting Minutes
              <span className="block text-blue-600">Generator</span>
            </h1>
            <p className="text-lg text-slate-500 leading-relaxed max-w-2xl mx-auto">
              Paste your meeting transcript and instantly get a professional, structured Minutes of Meeting document — complete with summaries, decisions, action items, and more.
            </p>

            {/* Feature pills */}
            <div className="flex flex-wrap justify-center gap-3 mt-8">
              {[
                { icon: <Zap className="w-3.5 h-3.5" />, label: 'Instant Results' },
                { icon: <Shield className="w-3.5 h-3.5" />, label: 'Secure & Private' },
                { icon: <Brain className="w-3.5 h-3.5" />, label: 'Gemini 1.5 Flash' },
              ].map(({ icon, label }) => (
                <div key={label} className="flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-slate-100 text-slate-600 text-xs font-medium">
                  {icon}
                  {label}
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Main tool */}
      <main className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="grid lg:grid-cols-2 gap-8 items-start">

          {/* Input Column */}
          <div className="space-y-4">
            <div>
              <label htmlFor="transcript" className="block text-sm font-semibold text-slate-700 mb-1.5">
                Meeting Transcript
              </label>
              <p className="text-xs text-slate-400 mb-3">
                Paste the full transcript of your meeting below. The AI will extract all key information.
              </p>
            </div>

            <div className="relative">
              <textarea
                id="transcript"
                value={transcript}
                onChange={(e) => {
                  setTranscript(e.target.value);
                  if (error) setError('');
                }}
                placeholder="Paste your meeting transcript here...

Example:
John: Good morning everyone. Let's start with the Q3 review.
Sarah: The sales numbers look promising, we hit 85% of our target...
..."
                rows={18}
                className="w-full rounded-2xl border border-slate-200 bg-white px-5 py-4 text-sm text-slate-700 placeholder:text-slate-300 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent resize-none transition-shadow scrollbar-thin shadow-sm"
              />
              {transcript && (
                <div className="absolute bottom-3 right-4 text-xs text-slate-300 pointer-events-none">
                  {transcript.length.toLocaleString()} chars
                </div>
              )}
            </div>

            {error && (
              <div className="flex items-center gap-2 px-4 py-3 rounded-xl bg-red-50 border border-red-100 text-red-600 text-sm">
                <div className="w-1.5 h-1.5 rounded-full bg-red-500 flex-shrink-0" />
                {error}
              </div>
            )}

            <button
              onClick={handleGenerate}
              disabled={loading}
              className="w-full flex items-center justify-center gap-2.5 px-6 py-4 rounded-2xl bg-blue-600 hover:bg-blue-700 active:bg-blue-800 text-white font-semibold text-base transition-all duration-150 shadow-lg shadow-blue-200 hover:shadow-blue-300 disabled:opacity-70 disabled:cursor-not-allowed disabled:shadow-none"
            >
              {loading ? (
                <>
                  <Loader2 className="w-5 h-5 animate-spin" />
                  Generating MOM...
                </>
              ) : (
                <>
                  <Sparkles className="w-5 h-5" />
                  Generate MOM
                  <ChevronRight className="w-4 h-4" />
                </>
              )}
            </button>

            {/* How it works */}
            <div className="rounded-2xl border border-slate-100 bg-white p-5 space-y-3">
              <p className="text-xs font-semibold text-slate-400 uppercase tracking-widest">How it works</p>
              <div className="space-y-2.5">
                {[
                  'Paste your raw meeting transcript',
                  'Click Generate MOM',
                  'Review the structured minutes',
                  'Copy or Download as Word document',
                ].map((step, i) => (
                  <div key={i} className="flex items-center gap-3 text-sm text-slate-600">
                    <span className="flex-shrink-0 w-5 h-5 rounded-full bg-blue-600 text-white text-xs flex items-center justify-center font-bold">
                      {i + 1}
                    </span>
                    {step}
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Output Column */}
          <div ref={momRef}>
            {!mom && !loading && (
              <div className="rounded-2xl border-2 border-dashed border-slate-200 bg-white p-12 flex flex-col items-center justify-center text-center min-h-[400px]">
                <div className="w-16 h-16 rounded-2xl bg-blue-50 flex items-center justify-center mb-4">
                  <Brain className="w-8 h-8 text-blue-300" />
                </div>
                <h3 className="font-semibold text-slate-400 mb-1.5">Your MOM will appear here</h3>
                <p className="text-sm text-slate-300 max-w-xs">
                  Paste a transcript and click Generate to see a professional Minutes of Meeting document.
                </p>
              </div>
            )}

            {loading && (
              <div className="rounded-2xl border border-slate-100 bg-white p-12 flex flex-col items-center justify-center text-center min-h-[400px] shadow-sm">
                <div className="relative mb-6">
                  <div className="w-16 h-16 rounded-full bg-blue-50 flex items-center justify-center">
                    <Brain className="w-8 h-8 text-blue-400" />
                  </div>
                  <div className="absolute -top-1 -right-1 w-5 h-5 rounded-full bg-blue-600 flex items-center justify-center">
                    <Loader2 className="w-3 h-3 text-white animate-spin" />
                  </div>
                </div>
                <h3 className="font-semibold text-slate-700 mb-1.5">Analyzing transcript...</h3>
                <p className="text-sm text-slate-400">Gemini AI is extracting key information from your meeting.</p>

                <div className="mt-6 flex flex-col items-center gap-2 text-xs text-slate-300">
                  {['Reading transcript', 'Identifying decisions', 'Extracting action items', 'Structuring document'].map((step, i) => (
                    <div key={i} className="flex items-center gap-2">
                      <div className="w-1 h-1 rounded-full bg-blue-300" />
                      {step}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {mom && !loading && (
              <div className="space-y-4">
                {/* Action buttons */}
                <div className="flex items-center justify-between">
                  <p className="text-sm font-semibold text-slate-700">Generated MOM</p>
                  <div className="flex gap-2">
                    <button
                      onClick={handleCopy}
                      className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-white border border-slate-200 hover:border-slate-300 text-slate-600 hover:text-slate-800 text-xs font-medium transition-all shadow-sm hover:shadow"
                    >
                      {copied ? (
                        <>
                          <Check className="w-3.5 h-3.5 text-emerald-500" />
                          <span className="text-emerald-600">Copied!</span>
                        </>
                      ) : (
                        <>
                          <Copy className="w-3.5 h-3.5" />
                          Copy
                        </>
                      )}
                    </button>
                    <button
                      onClick={handleDownload}
                      className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-blue-600 hover:bg-blue-700 text-white text-xs font-medium transition-all shadow-sm hover:shadow"
                    >
                      <Download className="w-3.5 h-3.5" />
                      Download Word
                    </button>
                  </div>
                </div>

                {/* MOM content */}
                <div className="bg-white rounded-2xl border border-slate-100 p-5 sm:p-6 shadow-sm">
                  <MOMDisplay mom={mom} generatedAt={generatedAt} />
                </div>

                {/* Regenerate */}
                <button
                  onClick={handleGenerate}
                  className="w-full flex items-center justify-center gap-2 px-4 py-3 rounded-xl border border-slate-200 bg-white hover:border-blue-200 hover:bg-blue-50 text-slate-500 hover:text-blue-600 text-sm font-medium transition-all"
                >
                  <Sparkles className="w-4 h-4" />
                  Regenerate
                </button>
              </div>
            )}
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-slate-100 bg-white mt-16">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-2">
              <div className="w-6 h-6 bg-blue-600 rounded-md flex items-center justify-center">
                <Brain className="w-3.5 h-3.5 text-white" />
              </div>
              <span className="font-bold text-slate-900">ROCK</span>
              <span className="text-blue-600 font-bold">MOM AI</span>
            </div>
            <p className="text-xs text-slate-400">
              Built with Gemini AI &bull; Crafted by <span className="font-semibold text-slate-500">Varun Jain</span>
            </p>
            <p className="text-xs text-slate-300">&copy; {new Date().getFullYear()} ROCK. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
